
[functions.wa-drip-campaign]
enabled = true
verify_jwt = false
import_map = "./functions/wa-drip-campaign/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/wa-drip-campaign/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/wa-drip-campaign/*.html" ]

[functions.generate-ai-content]
enabled = true
verify_jwt = false
import_map = "./functions/generate-ai-content/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/generate-ai-content/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/generate-ai-content/*.html" ]

[functions.receive-email-webhook]
enabled = true
verify_jwt = false
import_map = "./functions/receive-email-webhook/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/receive-email-webhook/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/receive-email-webhook/*.html" ]
